version: '3.8'
services:

  frontend:
    build: ./frontend
    ports:
      - '5173:80'

  backend:
    build: ./backend
    container_name: nexus-backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    networks:
      - nexus-net

networks:
  nexus-net:
    external: true
