FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY node_modules ./node_modules
COPY src ./src

RUN mkdir -p /tmp/nexus-pusher-uploads /app/data \
 && chgrp -R 0 /app /tmp/nexus-pusher-uploads \
 && chmod -R g=u /app /tmp/nexus-pusher-uploads

EXPOSE 3001
CMD ["node", "src/index.js"]
